<a href="https://colab.research.google.com/github/bala-codes/Numpy-Tensor-Torch-Operations-Visualized/blob/master/codes/Numpy_Tensor_Torch_Operations_Visualized.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
import torch

print(tf.__version__)
print(np.__version__)
print(torch.__version__)

2.3.0
1.18.5
1.6.0+cu101


<img src="https://cdn-images-1.medium.com/max/800/1*ommNjebqhFUWnWvcogfaAw.png">

# Array Initialization ~ 1D, 2D, 3D

<img src="https://cdn-images-1.medium.com/max/800/1*Ei4EFkk0qUh6RYq5cKQO4g.png">

## Scalar and 1-D Vector

In [2]:
# Numpy 
a = np.array(10)
print(a)
print(a.shape, a.dtype) # shape of the array and type of the elements
print()
a = np.array([10])
print(a)
print(a.shape, a.dtype) # shape of the array and type of the elements
print()
a = np.array([10], dtype=np.float32)
print(a)
print(a.shape, a.dtype) # shape of the array and type of the elements
print()

# TensorFlow
b = tf.constant(10) # As Scalar
print(b)
print()
b = tf.constant(10, shape=(1,1)) # As 1-D Vector
print(b)
print()
b = tf.constant(10, shape=(1,1), dtype=tf.float32) # As 1-D Vector with specified Data-type
print(b)

# Torch
c = torch.tensor(10, ) # As Scalar
print(c)
print()
c = torch.tensor([10]) # As 1-D Vector
print(c, c.shape, c.dtype)
print()
c = torch.tensor([10], dtype=torch.float32) # As 1-D Vector with specified Data-type
print(c)

10
() int64

[10]
(1,) int64

[10.]
(1,) float32

tf.Tensor(10, shape=(), dtype=int32)

tf.Tensor([[10]], shape=(1, 1), dtype=int32)

tf.Tensor([[10.]], shape=(1, 1), dtype=float32)
tensor(10)

tensor([10]) torch.Size([1]) torch.int64

tensor([10.])


## 2-D Vector

<img src="https://cdn-images-1.medium.com/max/800/1*SqK5t1Ud5ksMpmZQjT98AQ.png">

In [3]:
# Numpy
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(a.shape, a.dtype)
print()

# Tensorflow
b = tf.constant([[1,2,3], [4,5,6]])
print(b)
print(b.shape)
print()

# Torch
c = torch.tensor([[1,2,3], [4,5,6]]) 
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3) int64

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
(2, 3)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


# Generating data

<img src="https://cdn-images-1.medium.com/max/800/1*c2Wbf0ogAMz95AwFnLGYdw.png">

<img src="https://cdn-images-1.medium.com/max/800/1*7KjFTkEGGuBIVkB43h_fOg.png">

In [4]:
# Numpy
a = np.zeros((3,3))
print(a, a.shape, a.dtype)
print()
a = np.ones((3,3))
print(a, a.shape, a.dtype)
print()
a = np.eye(3)
print(a, a.shape, a.dtype)
print()
a = np.full((3,3),10.0)
print(a, a.shape, a.dtype)
print()

# Tensorflow
b = tf.zeros((3,3))
print(b)
print()
b = tf.ones((3,3))
print(b)
print()
b = tf.eye(3)
print(b)
print()
b = tf.fill([3,3], 10)
print(b)
print()

# Torch
c = torch.zeros((3,3))
print(c)
print()
c = torch.ones((3,3))
print(c)
print()
c = torch.eye(3)
print(c)
print()
c = c.new_full([3,3], 10)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] (3, 3) float64

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3) float64

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3) float64

[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]] (3, 3) float64

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)

tf.Tensor(
[[10 10 10]
 [10 10 10]
 [10 10 10]], shape=(3, 3), dtype=int32)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]])


# Draw random samples from normal distribution

<img src="https://cdn-images-1.medium.com/max/800/1*oroDC_aX76_G2V1zLV2DMQ.png">
<img src="https://cdn-images-1.medium.com/max/800/1*y3WMACw6HHqEAa-GG3cTdg.png">

In [5]:
# Numpy
a = np.random.randn(3,3) 
print(a, a.shape, a.dtype)
print()
print(a.mean(), a.std())
print()

# Tensorflow
b = tf.random.normal((3,3),mean=0, stddev=1)
print(b)
print()
print(tf.reduce_mean(b), tf.math.reduce_std(b))
print()

# Torch
c = torch.normal(mean=0, std=1, size=(3, 3))
print(c)
print()
print(torch.mean(c), torch.std(c))

[[-1.20474245  1.25303384 -0.36200896]
 [-1.65897476 -1.1378095  -1.27773511]
 [ 0.51973366 -0.51946521 -0.17489349]] (3, 3) float64

-0.5069846651973171 0.8875194677697864

tf.Tensor(
[[ 0.17814717 -0.80806047 -1.0725795 ]
 [ 1.3025515  -0.31631804 -0.10141616]
 [ 0.8401105   0.5194414  -0.97950065]], shape=(3, 3), dtype=float32)

tf.Tensor(-0.048624925, shape=(), dtype=float32) tf.Tensor(0.7856954, shape=(), dtype=float32)

tensor([[ 0.0978,  0.6083, -2.0741],
        [ 0.8155,  0.9387,  0.9400],
        [-0.2676,  0.0736,  0.0464]])

tensor(0.1309) tensor(0.9378)


# Draw samples from uniform distribution




<img src="https://cdn-images-1.medium.com/max/800/1*2aX6VCmTOk5_ojoVLTIVxw.png">
<img src="https://cdn-images-1.medium.com/max/800/1*vIcJ7bQLJw4vxQnuGkhBJA.png">

In [6]:
# Numpy
a = np.random.uniform(low=0, high=1, size=(3,3)) 
print(a, a.shape, a.dtype)
print()
print(a.mean(), a.std())
print()

# Tensorflow
b = tf.random.uniform((3,3), minval=0, maxval=1) # Values are always > 1
print(b)
print()
print(tf.reduce_mean(b), tf.math.reduce_std(b))
print()

# Torch
num_samples = 3
Dim = 3
c = torch.distributions.Uniform(0, +1).sample((num_samples, Dim))
print(c)
print()
print(torch.mean(c), torch.std(c))

[[0.90653086 0.71057116 0.72106348]
 [0.78497642 0.53240642 0.17899947]
 [0.63256464 0.21923118 0.2134137 ]] (3, 3) float64

0.5444174816147332 0.2591781239141793

tf.Tensor(
[[0.53188646 0.15539944 0.8736414 ]
 [0.02195573 0.77950466 0.15615916]
 [0.36707568 0.5003065  0.5270417 ]], shape=(3, 3), dtype=float32)

tf.Tensor(0.43477452, shape=(), dtype=float32) tf.Tensor(0.27169445, shape=(), dtype=float32)

tensor([[0.0344, 0.8858, 0.3127],
        [0.7995, 0.8993, 0.5918],
        [0.5000, 0.2346, 0.6114]])

tensor(0.5411) tensor(0.3012)


# Arrangements

<img src="https://cdn-images-1.medium.com/max/800/1*UnnY3jEq8qM1dXbD8US8Uw.png">

In [7]:
# Numpy
a = np.arange(0,9)
print(a)
print()
a = np.arange(start=1, stop=20, step=2, dtype=np.float32)
print(a, a.dtype)
print()

# Tensorflow
b = tf.range(9)
print(b)
print()
b = tf.range(start=1, limit=20, delta=2, dtype=tf.float64)
print(b)
print()

# Torch
c = torch.arange(start=0, end=9)
print(c)
print()
c = torch.arange(start=1, end=20, step=2, dtype=torch.float64)
print(c)


[0 1 2 3 4 5 6 7 8]

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.] float32

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)

tf.Tensor([ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.], shape=(10,), dtype=float64)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

tensor([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=torch.float64)


# Type - Conversion

In [8]:
# Numpy
a = a.astype(np.uint8)
print(a, a.dtype)
print()

# Tensorflow
b = tf.cast(b, dtype=tf.uint8)
print(b)
print()

# Torch
c = torch.tensor(c)
c= c.type(torch.int64)
print(c)

[ 1  3  5  7  9 11 13 15 17 19] uint8

tf.Tensor([ 1  3  5  7  9 11 13 15 17 19], shape=(10,), dtype=uint8)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  if sys.path[0] == '':


# Math Operations

<img src="https://cdn-images-1.medium.com/max/1200/1*9kVr15tL5ahesHZ0myh-uQ.png">
<img src="https://cdn-images-1.medium.com/max/800/1*PtEYTcCsJJzMOBXrFQmLuQ.png">
<img src="https://cdn-images-1.medium.com/max/1200/1*94Zw_BDp1fufWCd7_-qeVg.png">
<img src="https://cdn-images-1.medium.com/max/800/1*a29LnvI0cgn0gzaP1kPZ6Q.png">

In [9]:
# Numpy
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.add(a, b) # x + y
print(c, c.dtype)
print()
c = np.subtract(b,a) # y - x
print(c, c.dtype)
print()
c = np.divide(b,a) # y / x
print(c, c.dtype)
print()
c = np.multiply(b,a) # y * x
print(c, c.dtype)
print()
c = (a **2)
print(c)
print()

# Tensorflow
x = tf.constant([1,2,3,4,5])
y = tf.constant([6,7,8,9,10])
z = tf.add(x,y) # x + y
print(z)
print()
z = tf.subtract(y,x) # y - x
print(z)
print()
z = tf.divide(y,x) # y / x
print(z)
print()
z = tf.multiply(y,x) # y * x
print(z)
print()
z = (x **2)
print(z)
print()

# Torch
t = torch.tensor([1,2,3,4,5])
u = torch.tensor([6,7,8,9,10])
v = torch.add(t, u) # x + y
print(v)
print()
v = torch.sub(u,t) # y - x
print(v)
print()
v = torch.true_divide (u, t) # y / x
print(v)
print()
v = torch.mul(u,t) # y * x
print(v)
print()
v = (t **2)
print(v)

[ 7  9 11 13 15] int64

[5 5 5 5 5] int64

[6.         3.5        2.66666667 2.25       2.        ] float64

[ 6 14 24 36 50] int64

[ 1  4  9 16 25]

tf.Tensor([ 7  9 11 13 15], shape=(5,), dtype=int32)

tf.Tensor([5 5 5 5 5], shape=(5,), dtype=int32)

tf.Tensor([6.         3.5        2.66666667 2.25       2.        ], shape=(5,), dtype=float64)

tf.Tensor([ 6 14 24 36 50], shape=(5,), dtype=int32)

tf.Tensor([ 1  4  9 16 25], shape=(5,), dtype=int32)

tensor([ 7,  9, 11, 13, 15])

tensor([5, 5, 5, 5, 5])

tensor([6.0000, 3.5000, 2.6667, 2.2500, 2.0000])

tensor([ 6, 14, 24, 36, 50])

tensor([ 1,  4,  9, 16, 25])


# Dot Product

<img src="https://cdn-images-1.medium.com/max/800/1*Zyiav4DHpJRE52diaLmgQA.png">

In [10]:
# Numpy
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.dot(a, b) # x + y
print(c, c.dtype)
print()

# Tensorflow
x = tf.constant([1,2,3,4,5])
y = tf.constant([6,7,8,9,10])
z = tf.tensordot(x,y, axes=1)
print(z)
print()

# Torch
t = torch.tensor([1,2,3,4,5])
u = torch.tensor([6,7,8,9,10])
v = torch.dot(t,u)
print(v)

130 int64

tf.Tensor(130, shape=(), dtype=int32)

tensor(130)


<img src="https://cdn-images-1.medium.com/max/800/1*5D1UKW0bLcaQ3ZUN7sx3uA.png">

In [11]:
# Numpy
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
c = np.matmul(a,b) # (2,3) @ (3,3) --> (2,3) output shape
print(c)
print()

# Tensorflow
x = tf.constant([[1,2,3], [4,5,6]])
y = tf.constant([[1,2,3], [4,5,6], [7,8,9]])
z = tf.matmul(x,y) # (2,3) @ (3,3) --> (2,3) output shape
print(z)
print()

# Torch
t = torch.tensor([[1,2,3], [4,5,6]])
u = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
v = torch.matmul(t,u) # (2,3) @ (3,3) --> (2,3) output shape
print(v)

[[30 36 42]
 [66 81 96]]

tf.Tensor(
[[30 36 42]
 [66 81 96]], shape=(2, 3), dtype=int32)

tensor([[30, 36, 42],
        [66, 81, 96]])


# Indexing and Slicing

<img src="https://cdn-images-1.medium.com/max/800/1*Nmg32Jhd5XMxy1gZULd46A.png">

In [12]:
# Numpy
a = np.array([1,2,3,4,5,6,7,8])
print(a[:])
print(a[2:-3])
print(a[3:-1])
print(a[::2])
print()

# Tensorflow
b = tf.constant([1,2,3,4,5,6,7,8])
print(b[:])
print(b[2:-3])
print(b[3:-1])
print(b[::2])
print()

# Torch
c = torch.tensor([1,2,3,4,5,6,7,8])
print(c[:])
print(c[2:-3])
print(c[3:-1])
print(c[::2])

[1 2 3 4 5 6 7 8]
[3 4 5]
[4 5 6 7]
[1 3 5 7]

tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32)
tf.Tensor([3 4 5], shape=(3,), dtype=int32)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int32)
tf.Tensor([1 3 5 7], shape=(4,), dtype=int32)

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([3, 4, 5])
tensor([4, 5, 6, 7])
tensor([1, 3, 5, 7])


In [13]:
# Numpy
indices = np.array([0,3,5])
x_indices = a[indices]
print(x_indices)
print()

# Tensorflow
indices = tf.constant([0,3,5])
x_indices = tf.gather(b, indices)
print(x_indices)
print()

# Torch
indices = torch.tensor([0,3,5])
x_indices = c[indices]
print(x_indices)

[1 4 6]

tf.Tensor([1 4 6], shape=(3,), dtype=int32)

tensor([1, 4, 6])


<img src="https://cdn-images-1.medium.com/max/800/1*lgCTWIny8nGCxPNFjWMIPA.png">

In [14]:
# Numpy
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

# Matrix Indexing
# Print all individual Rows and Columns
print("Row-1",a[0, :])
print("Row-2",a[1, :])
print("Row-3",a[2, :])
print()
print("Col-1",a[:, 0])
print("Col-2",a[:, 1])
print("Col-3",a[:, 2])
print()

# Print the sub-diagonal matrix
print("Upper-Left",a[0:2,0:2])
print("Upper-Right",a[0:2,1:3])
print()
print("Bottom-Left",a[1:3,0:2])
print("Bottom-Right",a[1:3,1:3])


# Tensorflow
b = tf.constant([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

# Matrix Indexing
# Print all individual Rows and Columns
print("Row-1",b[0, :])
print("Row-2",b[1, :])
print("Row-3",b[2, :])
print()
print("Col-1",b[:, 0])
print("Col-2",b[:, 1])
print("Col-3",b[:, 2])
print()

# Print the sub-diagonal matrix
print("Upper-Left",b[0:2,0:2])
print("Upper-Right",b[0:2,1:3])
print()
print("Bottom-Left",b[1:3,0:2])
print("Bottom-Right",b[1:3,1:3])

# Torch
c = torch.tensor([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

# Matrix Indexing
# Print all individual Rows and Columns
print("Row-1",c[0, :])
print("Row-2",c[1, :])
print("Row-3",c[2, :])
print()
print("Col-1",c[:, 0])
print("Col-2",c[:, 1])
print("Col-3",c[:, 2])
print()

# Print the sub-diagonal matrix
print("Upper-Left",c[0:2,0:2])
print("Upper-Right",c[0:2,1:3])
print()
print("Bottom-Left",c[1:3,0:2])
print("Bottom-Right",c[1:3,1:3])

Row-1 [1 2 3]
Row-2 [4 5 6]
Row-3 [7 8 9]

Col-1 [1 4 7]
Col-2 [2 5 8]
Col-3 [3 6 9]

Upper-Left [[1 2]
 [4 5]]
Upper-Right [[2 3]
 [5 6]]

Bottom-Left [[4 5]
 [7 8]]
Bottom-Right [[5 6]
 [8 9]]
Row-1 tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Row-2 tf.Tensor([4 5 6], shape=(3,), dtype=int32)
Row-3 tf.Tensor([7 8 9], shape=(3,), dtype=int32)

Col-1 tf.Tensor([1 4 7], shape=(3,), dtype=int32)
Col-2 tf.Tensor([2 5 8], shape=(3,), dtype=int32)
Col-3 tf.Tensor([3 6 9], shape=(3,), dtype=int32)

Upper-Left tf.Tensor(
[[1 2]
 [4 5]], shape=(2, 2), dtype=int32)
Upper-Right tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)

Bottom-Left tf.Tensor(
[[4 5]
 [7 8]], shape=(2, 2), dtype=int32)
Bottom-Right tf.Tensor(
[[5 6]
 [8 9]], shape=(2, 2), dtype=int32)
Row-1 tensor([1, 2, 3])
Row-2 tensor([4, 5, 6])
Row-3 tensor([7, 8, 9])

Col-1 tensor([1, 4, 7])
Col-2 tensor([2, 5, 8])
Col-3 tensor([3, 6, 9])

Upper-Left tensor([[1, 2],
        [4, 5]])
Upper-Right tensor([[2, 3],
        [5, 6]])

Bo

# Reshaping

<img src="https://cdn-images-1.medium.com/max/800/1*CY6ulUvaIpBpefZL3aJj8w.png">

In [15]:
# Numpy
a = np.arange(9)
print(a)
a = np.reshape(a, (3,3))
print(a)
a = np.transpose(a, (1,0)) # Swap axes (1,0), use (0,1) nothing happens
print(a)
print()

# Tensorflow
b = tf.range(9)
print(b)
b = tf.reshape(b, (3,3))
print(b)
b = tf.transpose(b, perm=[1,0]) # Swap axes in perm (1,0), use (0,1) nothing happens
print(b)
print()

# Torch
c = torch.arange(9)
print(c)
c = torch.reshape(c, (3,3))
print(c)
c = c.permute(1,0) # Swap axes in perm (1,0), use (0,1) nothing happens
print(c)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


# Concatenation

<img src="https://cdn-images-1.medium.com/max/800/1*rJjgnsdb9AOfGUuxDRhaqA.png">

In [16]:
# Numpy
a = np.array([[1, 2], [3, 4]])
print("a",a)
b = np.array([[5, 6]])
print("b",b)
print()
d = np.concatenate((a, b), axis=0)
print("Concat (axis=0 - Row)")
print(d)
print()
e = np.concatenate((a, b.T), axis=1)
print("Concat (axis=1 - Column)")
print(e)
print()
print()

# Tensorflow
x = tf.constant([[1, 2], [3, 4]])
print("x",x)
y = tf.constant([[5, 6]])
print("y",y)
print()
z = tf.concat((x, y), axis=0)
print("Concat (axis=0 - Row)")
print(z)
print()
z = tf.concat((x, tf.transpose(y)), axis=1)
print("Concat (axis=1 - Column)")
print(z)
print()
print()

# Torch
t = torch.tensor([[1, 2], [3, 4]])
print("x",t)
u = torch.tensor([[5, 6]])
print("y",u)
print()
v = torch.cat((t , u), axis=0)
print("Concat (axis=0 - Row)")
print(v)
print()
v = torch.cat((t , u.T), axis=1)
print("Concat (axis=1 - Column)")
print(v)
print()


a [[1 2]
 [3 4]]
b [[5 6]]

Concat (axis=0 - Row)
[[1 2]
 [3 4]
 [5 6]]

Concat (axis=1 - Column)
[[1 2 5]
 [3 4 6]]


x tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
y tf.Tensor([[5 6]], shape=(1, 2), dtype=int32)

Concat (axis=0 - Row)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)

Concat (axis=1 - Column)
tf.Tensor(
[[1 2 5]
 [3 4 6]], shape=(2, 3), dtype=int32)


x tensor([[1, 2],
        [3, 4]])
y tensor([[5, 6]])

Concat (axis=0 - Row)
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Concat (axis=1 - Column)
tensor([[1, 2, 5],
        [3, 4, 6]])




# Summing across every axis

<img src="https://cdn-images-1.medium.com/max/800/1*9tTRW07UAXAkE1aFKM0GGA.png">

In [17]:
# Numpy
a = np.array([[1,2,3,4,5], [10,10,10,10,10]])
print(a)
print()
print("Overall flattened Sum", a.sum())
print("Sum across Columns",a.sum(axis=0)) 
print("Sum across Rows",a.sum(axis=1))
print()

# Tensorflow
b = tf.constant([[1,2,3,4,5], [10,10,10,10,10]])
print(b)
print()
print("Overall flattened Sum",tf.math.reduce_sum(b))
print("Sum across Columns",tf.math.reduce_sum(b, axis=0))
print("Sum across Rows",tf.math.reduce_sum(b, axis=1))
print()

# Torch
c = torch.tensor([[1,2,3,4,5], [10,10,10,10,10]])
print(c)
print()
print("Overall flattened  Sum",torch.sum(c))
print("Sum across Columns",torch.sum(c, axis=0))
print("Sum across Rows",torch.sum(c, axis=1))
print()

[[ 1  2  3  4  5]
 [10 10 10 10 10]]

Overall flattened Sum 65
Sum across Columns [11 12 13 14 15]
Sum across Rows [15 50]

tf.Tensor(
[[ 1  2  3  4  5]
 [10 10 10 10 10]], shape=(2, 5), dtype=int32)

Overall flattened Sum tf.Tensor(65, shape=(), dtype=int32)
Sum across Columns tf.Tensor([11 12 13 14 15], shape=(5,), dtype=int32)
Sum across Rows tf.Tensor([15 50], shape=(2,), dtype=int32)

tensor([[ 1,  2,  3,  4,  5],
        [10, 10, 10, 10, 10]])

Overall flattened  Sum tensor(65)
Sum across Columns tensor([11, 12, 13, 14, 15])
Sum across Rows tensor([15, 50])



# Taking mean across every axis

<img src="https://cdn-images-1.medium.com/max/800/1*-mEa_EJExGYgu_nbNXnK5Q.png">

In [18]:
# Numpy
a = np.array([[1,2,3,4,5], [10,10,10,10,10]])
print(a)
print()
print("Overall flattened mean", a.mean())
print("Sum across Columns",a.mean(axis=0)) 
print("Sum across Rows",a.mean(axis=1))
print()

# Tensorflow
b = tf.constant([[1,2,3,4,5], [10,10,10,10,10]])
print(b)
print()
print("Overall flattened mean",tf.math.reduce_mean(b))
print("Sum across Columns",tf.math.reduce_mean(b, axis=0))
print("Sum across Rows",tf.math.reduce_mean(b, axis=1))
print()

# Torch
c = torch.tensor([[1,2,3,4,5], [10,10,10,10,10]], dtype=torch.float32)
print(c)
print()
print("Overall flattened mean",torch.mean(c))
print("Sum across Columns",torch.mean(c, axis=0))
print("Sum across Rows",torch.mean(c, axis=1))

[[ 1  2  3  4  5]
 [10 10 10 10 10]]

Overall flattened mean 6.5
Sum across Columns [5.5 6.  6.5 7.  7.5]
Sum across Rows [ 3. 10.]

tf.Tensor(
[[ 1  2  3  4  5]
 [10 10 10 10 10]], shape=(2, 5), dtype=int32)

Overall flattened mean tf.Tensor(6, shape=(), dtype=int32)
Sum across Columns tf.Tensor([5 6 6 7 7], shape=(5,), dtype=int32)
Sum across Rows tf.Tensor([ 3 10], shape=(2,), dtype=int32)

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [10., 10., 10., 10., 10.]])

Overall flattened mean tensor(6.5000)
Sum across Columns tensor([5.5000, 6.0000, 6.5000, 7.0000, 7.5000])
Sum across Rows tensor([ 3., 10.])


# Dimension Expansion & move dimension

<img src="https://cdn-images-1.medium.com/max/800/1*dbkaG5dXETNEiZRqyIdlQw.png">

In [30]:
# Numpy
a = np.full((3,3),10.0)
print(a)
print(a.shape)
a = np.expand_dims(a, axis=0)
print(a)
print(a.shape)
b = np.full((3,3),20.0)
print(b)
b = np.expand_dims(b, axis=0)
print(b.shape)
c = np.concatenate((a,b), axis=0)
c = np.moveaxis(c,2,0) # Move 2nd dimension to 0th position
print(c)
print(c.shape)
print()

# Tensorflow
x = tf.fill((3,3),10.0)
print(x)
print(x.shape)
x = tf.expand_dims(x, axis=0)
print(x.shape)
y = tf.fill((3,3),20.0)
print(y)
print(y.shape)
y = tf.expand_dims(y, axis=0)
print(y.shape)
z = tf.concat((x,y), axis=0)
z = tf.transpose(z, [1, 0, 2])
print(z.shape)
print()

# Torch
m1 = torch.ones((2,), dtype=torch.int32)
m1 = m1.new_full((3, 3), 10)
m1 = torch.unsqueeze(m1, axis=0)
print(m1)
print(m1.shape)
m2 = torch.ones((2,), dtype=torch.int32)
m2 = m2.new_full((3, 3), 20)
print(m2)
m2 = torch.unsqueeze(m2, axis=0)
print(m2.shape)
m = torch.cat((m1,m2), axis=0)
m = m.permute([1,0,2])
print(m)
m.shape

[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
(3, 3)
[[[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]]
(1, 3, 3)
[[20. 20. 20.]
 [20. 20. 20.]
 [20. 20. 20.]]
(1, 3, 3)
[[[10. 10. 10.]
  [20. 20. 20.]]

 [[10. 10. 10.]
  [20. 20. 20.]]

 [[10. 10. 10.]
  [20. 20. 20.]]]
(3, 2, 3)

tf.Tensor(
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]], shape=(3, 3), dtype=float32)
(3, 3)
(1, 3, 3)
tf.Tensor(
[[20. 20. 20.]
 [20. 20. 20.]
 [20. 20. 20.]], shape=(3, 3), dtype=float32)
(3, 3)
(1, 3, 3)
(3, 2, 3)

tensor([[[10, 10, 10],
         [10, 10, 10],
         [10, 10, 10]]], dtype=torch.int32)
torch.Size([1, 3, 3])
tensor([[20, 20, 20],
        [20, 20, 20],
        [20, 20, 20]], dtype=torch.int32)
torch.Size([1, 3, 3])
tensor([[[10, 10, 10],
         [20, 20, 20]],

        [[10, 10, 10],
         [20, 20, 20]],

        [[10, 10, 10],
         [20, 20, 20]]], dtype=torch.int32)


torch.Size([3, 2, 3])

# MAX and ARGMAX

<img src="https://cdn-images-1.medium.com/max/800/1*C4zaaqb3a1R08uj23llLhw.png">

<img src="https://cdn-images-1.medium.com/max/800/1*fzoRQsZAq7SUp4wLFINB8g.png">
<img src="https://cdn-images-1.medium.com/max/1200/1*DbXyWegn3-sxnAeGQG-Azw.png">
<img src="https://cdn-images-1.medium.com/max/800/1*1DPeLiVtR95ziG3O4A_IUQ.png">

In [91]:
# Numpy
a = np.array([[5,10,15],
               [20,25,30]])
b = np.array([[6,69,35],
              [70,10,82]])
c = np.array([[25,45,48],
             [4,100,89]])
print(a)
final = np.zeros((3,2,3))
print(final.shape)
final[0, :, :] = a
final[1, :, :] = b
final[2, :, :] = c
print(final)
print("Overall flattened max", final.max())
print("max across Columns",final.max(axis=0)) 
print("max across Rows",final.max(axis=1))
print()
print("Index of max value across the flattened max", final.argmax())
print("Index of max value across Columns",final.argmax(axis=0)) 
print("Index of max value across Rows",final.argmax(axis=1)) 

# Tensorflow
final = tf.constant([[[5,10,15],
                  [20,25,30]],
                 [[6,69,35],
                  [70,10,82]],
                 [[25,45,48],
                  [4,100,89]]])
print(final)

print("Overall flattened max", tf.math.reduce_max(final))
print("max across Columns",tf.math.reduce_max(final,axis=0)) 
print("max across Rows",tf.math.reduce_max(final, axis=1))
print()
print("Index of max value across the flattened max", tf.math.argmax(final))
print("Index of max value across Columns",tf.math.argmax(final, axis=0)) 
print("Index of max value across Rows",tf.math.argmax(final, axis=1)) 

# Torch
final = torch.tensor([[[5,10,15],
                       [20,25,30]],
                      [[6,69,35],
                       [70,10,82]],
                      [[25,45,48],
                        [4,100,89]]])
print(final)

print("Overall flattened max", torch.max(final))
print("max across Columns",torch.max(final,axis=0)) 
print("max across Rows",torch.max(final, axis=1))
print()
print("Index of max value across the flattened max", torch.argmax(final))
print("Index of max value across Columns",torch.argmax(final, axis=0)) 
print("Index of max value across Rows",torch.argmax(final, axis=1)) 


[[ 5 10 15]
 [20 25 30]]
(3, 2, 3)
[[[  5.  10.  15.]
  [ 20.  25.  30.]]

 [[  6.  69.  35.]
  [ 70.  10.  82.]]

 [[ 25.  45.  48.]
  [  4. 100.  89.]]]
Overall flattened max 100.0
max across Columns [[ 25.  69.  48.]
 [ 70. 100.  89.]]
max across Rows [[ 20.  25.  30.]
 [ 70.  69.  82.]
 [ 25. 100.  89.]]

Index of max value across the flattened max 16
Index of max value across Columns [[2 1 2]
 [1 2 2]]
Index of max value across Rows [[1 1 1]
 [1 0 1]
 [0 1 1]]
tf.Tensor(
[[[  5  10  15]
  [ 20  25  30]]

 [[  6  69  35]
  [ 70  10  82]]

 [[ 25  45  48]
  [  4 100  89]]], shape=(3, 2, 3), dtype=int32)
Overall flattened max tf.Tensor(100, shape=(), dtype=int32)
max across Columns tf.Tensor(
[[ 25  69  48]
 [ 70 100  89]], shape=(2, 3), dtype=int32)
max across Rows tf.Tensor(
[[ 20  25  30]
 [ 70  69  82]
 [ 25 100  89]], shape=(3, 3), dtype=int32)

Index of max value across the flattened max tf.Tensor(
[[2 1 2]
 [1 2 2]], shape=(2, 3), dtype=int64)
Index of max value across Columns